name: Updates music-box
on:
  schedule:
    - cron: '*/10 * * * *'
  push:
    branches: master
jobs:
  update:
   runs-on: ubuntu-latest
   steps:
     - name: Update
       uses: jacc/music-box@master
       env:
          LASTFM_KEY: ${{ secrets.LASTFM_KEY }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEEN }}
          LFMUSERNAME: venoras
          GIST_ID: 3e639ee012f36d267afc87c9632727b3
